export const DICE_BEAR_PREFIX = 'dice-bear:'

export const DICE_BEAR_AVATAR = [
	'adventurer',
	'adventurer-neutral',
	'avataaars',
	'avataaars-neutral',
	'big-ears',
	'big-ears-neutral',
	'big-smile',
	'bottts',
	'bottts-neutral',
	'croodles',
	'croodles-neutral',
	'dylan',
	'fun-emoji',
	'glass',
	'icons',
	'identicon',
	'initials',
	'lorelei',
	'lorelei-neutral',
	'micah',
	'miniavs',
	'notionists',
	'notionists-neutral',
	'open-peeps',
	'personas',
	'pixel-art',
	'pixel-art-neutral',
	'rings',
	'shapes',
	'thumbs',
	'toon-head',
] as const
